-- TASK 1

CREATE TABLE STUDENT1(
    STUDENT_ID INTEGER PRIMARY KEY,
    SURNAME_STUDENT VARCHAR(10) NOT NULL,
    NAME_STUDENT VARCHAR(10) NOT NULL,
    UNIV_NAME VARCHAR(10),
    STIPEND INTEGER
);

CREATE TABLE EXAM1(
    STUDENT_ID INTEGER PRIMARY KEY,
    SUBJ_NAME VARCHAR(10) NOT NULL,
    MARK INTEGER,
    NAME_LECTURER VARCHAR(10) 
);

-- TASK 2
INSERT INTO STUDENT1 VALUES(  1, 'MAKUTA','MAKS',     'VNU',  5000);
INSERT INTO STUDENT1 VALUES( 11,  'ZAYEC','ANATOLI',  'LNTU', 1250);
INSERT INTO STUDENT1 VALUES(121, 'POPLAV','BORIS',    'VNU',  3600);
INSERT INTO STUDENT1 VALUES( 31, 'VILSON','JONH',     'LNTU', 950);
INSERT INTO STUDENT1 VALUES(  4,'SCARLET','CRISTINNA','VNU',  6100);

INSERT INTO EXAM1 VALUES(  4,'MATH',2,'SOLOVYOV');
INSERT INTO EXAM1 VALUES( 11,'PROG',3,'GLINAZ');
INSERT INTO EXAM1 VALUES( 56,'MATH',5,'SOLOVYOV');
INSERT INTO EXAM1 VALUES(121,'PROG',3,'GLINAZ');
INSERT INTO EXAM1 VALUES( 15,'PROG',4,'GLINAZ');

-- TASK 3
ALTER TABLE STUDENT1 ADD REMARK VARCHAR(10);

-- TASK 4

UPDATE STUDENT1 SET STIPEND = 2 * STIPEND WHERE UNIV_NAME = 'VNU';

-- TASK 5
-- ...

-- TASK 6
DROP TABLE STUDENT1;
DROP TABLE EXAM1; 

